### PR TITLE
[bugfix] argument decorators were broken in >= 3.0.0

### PR DESCRIPTION
**Pull request by kybishop**

### CODE REVIEW

**Comment by buschtoens** [comment]
Can confirm that `@argument` works. :tada: 

However [`-/debug/decorators/*.js`](https://github.com/ember-decorators/argument/tree/0409daef6c4b64d1735eb6a1aa3225752578edd3/addon/-debug/decorators) need some changes too. In particular, `@type` still returned a `ComputedProperty` instance when directly accessing it. Since all rely on [`-debug/utils/validation-decorators.js`](https://github.com/ember-decorators/argument/blob/0409daef6c4b64d1735eb6a1aa3225752578edd3/addon/-debug/utils/validation-decorator.js), I guess this is where to put the fix as well? :)

**Comment by pzuraq** [comment]
You are correct, hadn't looked at those. We'll merge this and do that fix in a separate PR, and we should add some tests in 3.1+ that verify that ES5 getters work as expected

**Comment by kybishop** [comment]
Anything I could do to help this along? Consumers of ember-bootstrap and ember-attacher are currently blocked on using Ember 3.x until this is released, would love to help them out.

**Comment by pzuraq** [comment]
@kybishop I'm going to try to dig in today before I leave, if I can't I'll merge and release this at the least before then

**Comment by pzuraq** [comment]
Closing in favor of #63

**Pull request closed without merging**
