### PR TITLE
Make Compatible with Ember 3.9

### PR DESCRIPTION
**Pull request by alexlafroscia**

### CODE REVIEW

**Comment by pzuraq** [comment]
You should hold off on merging this, the changes in 3.9 will be reverted and pushed until 3.10

**Comment by pzuraq** [comment]
https://github.com/emberjs/ember.js/pull/17649

**Comment by pzuraq** [comment]
I would keep the PR open for 3.10 though, the architecture should be the same

**Comment by alexlafroscia** [comment]
Ah, I see. Good to know -- I was trolled by the `ember-concurrency` incompatibility, too!

I'll drop that commit but keep it around for now, since I'd like to do these other dependency upgrades anyway.

**Pull request closed without merging**
